✨ notification with ntfy
I-Al-Istannen/Lighthouse pull request #3
Opened 2023-03-15 21:32 UTC by libaurea

Notifications with ntfy instead of discord. Currently not tested.

2023-03-15 22:03 UTC, libaurea commented
Works :)
![image](https://user-images.githubusercontent.com/68400683/225453821-a6fb24a1-85af-496a-acbe-23e167baee8a.png)

2023-03-15 22:23 UTC, libaurea commented
An example in mobile view with the latest changes.
![11yTB8hc3st6](https://user-images.githubusercontent.com/68400683/225456878-26c7f6a3-e600-40bd-8d80-ac532d2d0bfb.jpg)

2023-03-15 22:28 UTC, libaurea commented
It would also be possible to include [message priorities](https://docs.ntfy.sh/publish/#message-priority) and [authentication](https://docs.ntfy.sh/publish/#authentication).

2023-03-15 22:40 UTC, I-Al-Istannen approved these changes

2023-03-19 13:56 UTC, libaurea commented
Example interaction
![image](https://user-images.githubusercontent.com/68400683/226180833-c6d6741f-e7b9-463f-84cb-9b3d438a8565.png)

2023-03-19 20:41 UTC, I-Al-Istannen requested changes

2023-03-19 20:41 UTC, I-Al-Istannen commented on src/main/java/de/ialistannen/lighthouse/cli/CliArguments.java
>    String webhookUrlOrToken();
This can now also take a ntfy webhook URL, right? Can you add that to the description?

2023-03-19 21:27 UTC, I-Al-Istannen approved these changes

2023-03-19 21:33 UTC, merged